### ISSUE TITLE
Ajout de liaisons (LiveBindings)

### ISSUE THREAD

**Issue by Serge-Girard** [Remi1945/visulabo#1]
J'ai tenté avec succès l'ajout de liaisons (LiveBindings) sur le composant TThermometre
![Capture](https://user-images.githubusercontent.com/51124639/115949335-c16b7880-a4d4-11eb-8b36-18ae6e35219b.PNG)
Mais aussi sur tous les autres composants utilisant une propriété Valeur TJaugeCir, TBoussole, TAffichage7Seg  et même TLed en utilisant la même technique de code
![Capture](https://user-images.githubusercontent.com/51124639/115950199-355c4f80-a4da-11eb-9432-666c606c2a0b.PNG)

À mon avis ajouter cette possibilité est un incontournable en FMX. 
[Modifs.zip](https://github.com/Remi1945/visulabo/files/6369077/Modifs.zip)

Plusieurs regrets cependant, seul TThermometre  m'a permis de lier d'autres propriétés (je n'ai pas cherché le pourquoi)

Quelques constatations sur les composants :
Au design, il faudrait une taille par défaut plus grande (TThermometre, TBoussole, TJaugeCir sont trop écrasées.
On ne peut pas modifier le gradient Off de TLed. Je n'ai pas réussi à montrer les valeurs des graduations majeures dans TBoussole

**Comment by Remi1945** [comment]
Pour ce qui est des valeurs des graduations de la boussole c'est dans le paramètre textsettings actuellement la couleur par défaut est noir et comme le fond est noir 
Pour la led j'ai forcé le gradient car je voulais un effet de brillance

**Comment by Serge-Girard** [comment]
Il m'a fallu du temps pour trouver comment ne pas avoir, par défaut, un lien bidirectionnel. 
La solution est d'utiliser la fonction RegisterValuePropertyName au lieu  de RegisterObservableMember 
exemple : 
`initialization
Data.Bind.Components.RegisterValuePropertyName
  (TArray<TClass>.create(TThermometre), 'Valeur', 'FMX');

finalization
Data.Bind.Components.UnRegisterValuePropertyName
  (TArray<TClass>.create(TThermometre)); `

cela me parait alors plus juste au niveau du concepteur visuel de liens 
![Capture](https://user-images.githubusercontent.com/51124639/146149467-dff2b9da-b9d9-4539-a7f8-e0670dc4f260.PNG)
